import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';

import 'models/booking.dart';
import 'models/car.dart';
import 'providers/auth_provider.dart';
import 'providers/booking_provider.dart';
import 'providers/ui_provider.dart';
import 'router/app_router.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Set preferred orientations (optional)
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Initialize Hive
  await Hive.initFlutter();

  // Register Hive adapters (generated by build_runner)
  // Note: Run 'flutter pub run build_runner build' to generate adapters
  Hive.registerAdapter(CarAdapter());
  Hive.registerAdapter(BookingAdapter());
  Hive.registerAdapter(BookingStatusAdapter());

  // Open Hive boxes
  await Hive.openBox<Booking>('bookings');

  // Create providers
  final authProvider = AuthProvider();
  final bookingProvider = BookingProvider();
  final uiProvider = UIProvider();

  // Initialize router with AuthProvider
  initializeAppRouter(authProvider);

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider.value(value: authProvider),
        ChangeNotifierProvider.value(value: bookingProvider),
        ChangeNotifierProvider.value(value: uiProvider),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Car Rental',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          brightness: Brightness.light,
        ),
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          brightness: Brightness.dark,
        ),
      ),
      themeMode: ThemeMode.light,
      routerConfig: appRouter,
    );
  }
}
